# Generated by Django 4.1 on 2023-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="img",
            field=models.ImageField(default=2, upload_to="img/%y"),
            preserve_default=False,
        ),
    ]
